apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: reasonable-hyena-java-springboot
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/rhtap-qe:738e2fc275b0b0e274e86c6a99813b37e7f40b95@sha256:96d8da7e9a16962c4ceba09aedff8cfb4bad388d90b58882b97d0998f14c5336
        name: container-image  
